-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 20:31:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `descCategoria` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `estado_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado_producto` (
  `idestado_producto` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idestado_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `categorias_idcategorias` INT NOT NULL,
  `estado_producto_idestado_producto` INT NOT NULL,
  `nombreProducto` VARCHAR(70) NOT NULL,
  `codigoProducto` VARCHAR(45) NULL,
  `sku` VARCHAR(45) NULL,
  `costoProducto` DOUBLE NULL,
  `precioProducto` DOUBLE NULL,
  `marcaProducto` VARCHAR(45) NULL,
  `modeloProducto` VARCHAR(45) NULL,
  `cantidadProducto` DOUBLE NULL,
  `ivaProducto` FLOAT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_categorias1_idx` (`categorias_idcategorias` ASC) ,
  INDEX `fk_productos_estado_producto1_idx` (`estado_producto_idestado_producto` ASC) ,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_estado_producto1`
    FOREIGN KEY (`estado_producto_idestado_producto`)
    REFERENCES `estado_producto` (`idestado_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `documentoCliente` VARCHAR(45) NOT NULL,
  `tipoDocCliente` VARCHAR(45) NULL,
  `nombresCliente` VARCHAR(45) NULL,
  `apellidosCliente` VARCHAR(45) NULL,
  `direccionCliente` VARCHAR(45) NULL,
  `telefonoCliente` VARCHAR(45) NULL,
  `correoCliente` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `numeroVenta` INT NOT NULL,
  `clientes_idclientes` INT NOT NULL,
  `fechaVenta` DATE NULL,
  `dctoVenta` FLOAT NULL,
  `ivaVenta` FLOAT NULL,
  `totalVenta` DOUBLE NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventas_clientes1_idx` (`clientes_idclientes` ASC) ,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataforma_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_venta` (
  `idplataforma_venta` INT NOT NULL AUTO_INCREMENT,
  `nom_plataforma` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idplataforma_venta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalleVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalleVentas` (
  `idDetalleVentas` INT NOT NULL AUTO_INCREMENT,
  `ventas_idventas` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  `plataforma_venta_idplataforma_venta` INT NOT NULL,
  `precioProducto` DOUBLE NOT NULL,
  `cantProducto` DOUBLE NOT NULL,
  `subtotalVenta` DOUBLE NULL,
  `dctoProducto` FLOAT NULL,
  `otrosImpuestos` FLOAT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idDetalleVentas`),
  INDEX `fk_detalleVentas_ventas1_idx` (`ventas_idventas` ASC) ,
  INDEX `fk_detalleVentas_productos1_idx` (`productos_idproductos` ASC) ,
  INDEX `fk_detalleVentas_plataforma_venta1_idx` (`plataforma_venta_idplataforma_venta` ASC) ,
  CONSTRAINT `fk_detalleVentas_ventas1`
    FOREIGN KEY (`ventas_idventas`)
    REFERENCES `ventas` (`idventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVentas_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleVentas_plataforma_venta1`
    FOREIGN KEY (`plataforma_venta_idplataforma_venta`)
    REFERENCES `plataforma_venta` (`idplataforma_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proveedores` (
  `idproveedores` INT NOT NULL AUTO_INCREMENT,
  `docProveedor` VARCHAR(45) NOT NULL,
  `nombresProveedor` VARCHAR(45) NULL,
  `apellidosProveedor` VARCHAR(45) NULL,
  `direccionProveedor` VARCHAR(45) NULL,
  `telefonoProveedor` VARCHAR(45) NULL,
  `celularProveedor` VARCHAR(45) NULL,
  `correoProveedor` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idproveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras` (
  `idcompras` INT NOT NULL AUTO_INCREMENT,
  `numeroCompra` INT NOT NULL,
  `proveedores_idproveedores` INT NOT NULL,
  `fechaCompra` DATE NULL,
  `totalCompra` DOUBLE NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idcompras`),
  INDEX `fk_compras_proveedores1_idx` (`proveedores_idproveedores` ASC) ,
  CONSTRAINT `fk_compras_proveedores1`
    FOREIGN KEY (`proveedores_idproveedores`)
    REFERENCES `proveedores` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `detalleCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalleCompras` (
  `iddetalleCompras` INT NOT NULL AUTO_INCREMENT,
  `compras_idcompras` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  `cantidadProductos` DOUBLE NOT NULL,
  `ivaProducto` FLOAT NULL,
  `subtotalCompra` DOUBLE NULL,
  `observacionesCompra` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`iddetalleCompras`),
  INDEX `fk_detalleCompras_compras_idx` (`compras_idcompras` ASC) ,
  INDEX `fk_detalleCompras_productos1_idx` (`productos_idproductos` ASC) ,
  CONSTRAINT `fk_detalleCompras_compras`
    FOREIGN KEY (`compras_idcompras`)
    REFERENCES `compras` (`idcompras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleCompras_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
